// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2cdX39PdMt8AdQ95KKb4AY5urdCVIgg',
    appId: '1:1013761371713:web:b722bd14eb262764dae0c0',
    messagingSenderId: '1013761371713',
    projectId: 'membermanagementsystem-b345b',
    authDomain: 'membermanagementsystem-b345b.firebaseapp.com',
    storageBucket: 'membermanagementsystem-b345b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDGX0vwGz3KEJP71_K8o2tapnj9YStoak',
    appId: '1:1013761371713:android:797651c2fed13017dae0c0',
    messagingSenderId: '1013761371713',
    projectId: 'membermanagementsystem-b345b',
    storageBucket: 'membermanagementsystem-b345b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARenKgTtg78xghlrl2-A6meDTcYbBgrpY',
    appId: '1:1013761371713:ios:81fc256d85c41203dae0c0',
    messagingSenderId: '1013761371713',
    projectId: 'membermanagementsystem-b345b',
    storageBucket: 'membermanagementsystem-b345b.firebasestorage.app',
    iosBundleId: 'com.example.memberManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARenKgTtg78xghlrl2-A6meDTcYbBgrpY',
    appId: '1:1013761371713:ios:81fc256d85c41203dae0c0',
    messagingSenderId: '1013761371713',
    projectId: 'membermanagementsystem-b345b',
    storageBucket: 'membermanagementsystem-b345b.firebasestorage.app',
    iosBundleId: 'com.example.memberManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf2cdX39PdMt8AdQ95KKb4AY5urdCVIgg',
    appId: '1:1013761371713:web:3a256dac21695997dae0c0',
    messagingSenderId: '1013761371713',
    projectId: 'membermanagementsystem-b345b',
    authDomain: 'membermanagementsystem-b345b.firebaseapp.com',
    storageBucket: 'membermanagementsystem-b345b.firebasestorage.app',
  );
}
